# Generated by Django 4.2.7 on 2025-08-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
